---
- name: reinstall consul
  when: hostvars[inventory_hostname].ansible_local.hitotito_consul.consul.version != consul_ver or consul_force_reinstall
  block:
    - name: remove old binary install
      file: 
        path: "{{ consul_bin_dir }}/consul"
        state: absent

    - name: install unzip
      apt:
        name: zip
        state: present

    - name: create consul directory structure
      with_items:
        - "{{ consul_bin_dir }}"
        - "{{ consul_conf_agent_dir }}"
        - "{{ consul_data_dir }}"
        - "{{ consul_systemd_dir }}"
        - "{{ consul_os_pid_dir }}"
      file:
        path: "{{ item }}"
        state: directory
        mode: 0750
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"

    - name: download consul
      get_url:
        url: '{{consul_url}}'
        dest: "/tmp/{{consul_zip}}"
        checksum: '{{consul_checksum}}'
        mode: 0644

    - name: unarchive consul
      unarchive:
        remote_src: yes
        src: /tmp/{{consul_zip}}
        dest: '{{consul_bin_dir}}'
        creates: '{{consul_bin_dir}}/consul'
        group: '{{ consul_group }}'
        owner: '{{ consul_user }}'
  always:
    - name: cleanup
      file:
        path: /tmp/{{consul_zip}}
        state: absent

- name: install consul-agent systemd service file
  template:
    src: "consul-agent.service.j2"
    dest: "{{ consul_systemd_dir }}/consul-agent.service"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify:
    - restart consul-agent

- name: create symlink
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - src: "{{ consul_bin_dir }}/consul"
      dest: "{{ consul_os_install_dir }}/consul"
    - src: "{{ consul_systemd_dir }}/consul-agent.service"
      dest: "{{ consul_os_systemd_dir }}/consul-agent.service"
  notify:
    - restart consul-agent

- name: Enable consul-agent systemd service
  systemd:
    name: consul-agent
    daemon_reload: yes
    enabled: yes
